PRAGMA foreign_keys = ON;

-- brands
CREATE TABLE IF NOT EXISTS brands (
    id TEXT PRIMARY KEY,
        name TEXT,
            team_id TEXT
            );

            -- cytometers
            CREATE TABLE IF NOT EXISTS cytometers (
                id TEXT PRIMARY KEY,
                    name TEXT,
                        manufacturer TEXT,
                            model TEXT,
                                serial_number TEXT,
                                    created_at TEXT,
                                        team_id TEXT
                                        );

                                        -- optical_channels
                                        CREATE TABLE IF NOT EXISTS optical_channels (
                                            id TEXT PRIMARY KEY,
                                                name TEXT,
                                                    min_range INTEGER,
                                                        max_range INTEGER,
                                                            team_id TEXT
                                                            );

                                                            -- fluorochromes
                                                            CREATE TABLE IF NOT EXISTS fluorochromes (
                                                                id TEXT PRIMARY KEY,
                                                                    name TEXT
                                                                    );

                                                                    -- reagents (anticuerpos)
                                                                    CREATE TABLE IF NOT EXISTS reagents (
                                                                        id TEXT PRIMARY KEY,
                                                                            name TEXT,
                                                                                fluorochrome TEXT,
                                                                                    brand_id TEXT,
                                                                                        catalog_number TEXT,
                                                                                            clone TEXT,
                                                                                                price REAL,
                                                                                                    team_id TEXT,
                                                                                                        user_id TEXT
                                                                                                        );

                                                                                                        -- general_reagents
                                                                                                        CREATE TABLE IF NOT EXISTS general_reagents (
                                                                                                            id TEXT PRIMARY KEY,
                                                                                                                name TEXT,
                                                                                                                    brand_id TEXT,
                                                                                                                        type TEXT,
                                                                                                                            concentration TEXT,
                                                                                                                                preparation_date TEXT,
                                                                                                                                    notes TEXT,
                                                                                                                                        created_at TEXT,
                                                                                                                                            arrival_date TEXT,
                                                                                                                                                expiration_date TEXT,
                                                                                                                                                    price REAL,
                                                                                                                                                        team_id TEXT,
                                                                                                                                                            user_id TEXT
                                                                                                                                                            );

                                                                                                                                                            -- reagent_units (viales de anticuerpos)
                                                                                                                                                            CREATE TABLE IF NOT EXISTS reagent_units (
                                                                                                                                                                id TEXT PRIMARY KEY,
                                                                                                                                                                    reagent_id TEXT,
                                                                                                                                                                        initial_volume REAL,
                                                                                                                                                                            arrival_date TEXT,
                                                                                                                                                                                expiration_date TEXT,
                                                                                                                                                                                    status TEXT,
                                                                                                                                                                                        lot TEXT,
                                                                                                                                                                                            team_id TEXT
                                                                                                                                                                                            );

                                                                                                                                                                                            -- general_reagent_units (viales de reactivos generales)
                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS general_reagent_units (
                                                                                                                                                                                                id TEXT PRIMARY KEY,
                                                                                                                                                                                                    general_reagent_id TEXT,
                                                                                                                                                                                                        lot_number TEXT,
                                                                                                                                                                                                            expiration_date TEXT,
                                                                                                                                                                                                                location TEXT,
                                                                                                                                                                                                                    status TEXT,
                                                                                                                                                                                                                        volume REAL,
                                                                                                                                                                                                                            notes TEXT,
                                                                                                                                                                                                                                created_at TEXT,
                                                                                                                                                                                                                                    updated_at TEXT,
                                                                                                                                                                                                                                        team_id TEXT
                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                        -- panels
                                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS panels (
                                                                                                                                                                                                                                            id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                                name TEXT,
                                                                                                                                                                                                                                                    category_id TEXT,
                                                                                                                                                                                                                                                        description TEXT,
                                                                                                                                                                                                                                                            sample_volume REAL,
                                                                                                                                                                                                                                                                created_at TEXT,
                                                                                                                                                                                                                                                                    status TEXT,
                                                                                                                                                                                                                                                                        cytometer_id TEXT,
                                                                                                                                                                                                                                                                            washed_sample INTEGER,
                                                                                                                                                                                                                                                                                acquisition_protocol_status TEXT,
                                                                                                                                                                                                                                                                                    acquisition_protocol_name TEXT,
                                                                                                                                                                                                                                                                                        acquisition_protocol_code TEXT,
                                                                                                                                                                                                                                                                                            compensation_status TEXT,
                                                                                                                                                                                                                                                                                                compensation_name TEXT,
                                                                                                                                                                                                                                                                                                    compensation_code TEXT,
                                                                                                                                                                                                                                                                                                        analysis_protocol_status TEXT,
                                                                                                                                                                                                                                                                                                            analysis_protocol_name TEXT,
                                                                                                                                                                                                                                                                                                                analysis_protocol_code TEXT,
                                                                                                                                                                                                                                                                                                                    team_id TEXT,
                                                                                                                                                                                                                                                                                                                        user_id TEXT
                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                        -- panel_reagents
                                                                                                                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS panel_reagents (
                                                                                                                                                                                                                                                                                                                            id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                panel_id TEXT,
                                                                                                                                                                                                                                                                                                                                    reagent_id TEXT,
                                                                                                                                                                                                                                                                                                                                        optical_channel_id TEXT,
                                                                                                                                                                                                                                                                                                                                            volume_used REAL,
                                                                                                                                                                                                                                                                                                                                                assigned_at TEXT,
                                                                                                                                                                                                                                                                                                                                                    is_intracellular INTEGER,
                                                                                                                                                                                                                                                                                                                                                        display_name TEXT,
                                                                                                                                                                                                                                                                                                                                                            team_id TEXT
                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                            -- panel_general_reagents
                                                                                                                                                                                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS panel_general_reagents (
                                                                                                                                                                                                                                                                                                                                                                id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                    panel_id TEXT,
                                                                                                                                                                                                                                                                                                                                                                        general_reagent_id TEXT,
                                                                                                                                                                                                                                                                                                                                                                            volume_used REAL,
                                                                                                                                                                                                                                                                                                                                                                                notes TEXT,
                                                                                                                                                                                                                                                                                                                                                                                    added_at TEXT,
                                                                                                                                                                                                                                                                                                                                                                                        team_id TEXT
                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                        -- purchase_orders
                                                                                                                                                                                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS purchase_orders (
                                                                                                                                                                                                                                                                                                                                                                                            id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                supplier TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                    total_price REAL,
                                                                                                                                                                                                                                                                                                                                                                                                        status TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                            created_at TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                updated_at TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                    team_id TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                        user_id TEXT
                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                        -- purchase_order_items
                                                                                                                                                                                                                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS purchase_order_items (
                                                                                                                                                                                                                                                                                                                                                                                                                            id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                                purchase_order_id TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                    reagent_id TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                        quantity INTEGER,
                                                                                                                                                                                                                                                                                                                                                                                                                                            unit_price REAL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                total_price REAL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    status TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        received_quantity INTEGER,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            team_id TEXT
                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- cytometer_optical_channels
                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS cytometer_optical_channels (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cytometer_id TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        optical_channel_id TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            associated_fluorochrome TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                team_id TEXT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                